#!/bin/bash

# Get the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $DIR

# Open Xhost
xhost +local:

# Environment variables
export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:=100}

# Initialize docker environment
cd ./docker
docker compose up

# Clean up docker after exit
docker compose down

# Clean up Xhost
xhost -local:
